version: '3.5'

services:
    app:
        build:
            context: .
            target: production
        ports:
            - "8080:8080"
        environment:
            TZ: Europe/Paris
            AUTH_TOKEN: TimeToTest

    sut:
        image: alpine
        depends_on:
            - app
        command: /test.sh
        volumes:
            - "./test.sh:/test.sh:ro"
