version: '3.5'

services:
    app:
        build:
            context: .
            target: production
        ports:
            - "8080:8080"
        environment:
            TZ: Europe/Paris
            AUTH_TOKEN: SomeHash
