version: '3.5'

networks:
    sfbundles-network:
        external: true

services:
    app:
        build: .
        networks:
            sfbundles-network:
                aliases:
                    - chrome-to-pdf
        environment:
            TZ: Europe/Paris
            AUTH_TOKEN: SomeHash
