parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\Controller\Controller:
        arguments:
            - '@App\Pdf\Factory'
            - '%env(string:AUTH_TOKEN)%'
        public: true

    App\EventListener\KernelListener:
        arguments:
            - '@App\Pdf\Factory'
        tags:
            - name: kernel.listener
              event: kernel.terminate
              method: onTerminate

    App\Pdf\Factory: ~
