parameters:

services:
    app.factory:
        class: HeadlessChromium\BrowserFactory
        arguments:
            - '%env(string:CHROME_BINARY)%'

    app.browser:
        class: HeadlessChromium\Browser\ProcessAwareBrowser
        factory: ['@app.factory', 'createBrowser']
        arguments:
            -   noSandbox: true

    app.generator:
        class: App\Pdf\Generator
        arguments:
            - '@app.browser'

    app.controller:
        class: App\Controller\Controller
        arguments:
            - '@app.generator'
            - '%env(string:AUTH_TOKEN)%'
        public: true

    app.listener.kernel:
        class: App\Listener\KernelListener
        arguments:
            - '@app.browser'
        tags:
            - name: kernel.event_listener
              event: kernel.terminate

when@dev:
    services:
        app.command.generate:
            class: App\Command\GenerateCommand
            arguments:
                - '@app.generator'
            tags:
                - 'console.command'

        app.browser:
            class: HeadlessChromium\Browser\ProcessAwareBrowser
            factory: [ '@app.factory', 'createBrowser' ]
            arguments:
                -   noSandbox: true
                    ignoreCertificateErrors: true
                    debugLogger: '@logger'

        app.controller.test:
            class: App\Controller\TestController
            arguments:
                - '@app.generator'
            public: true
