when@dev:
    monolog:
        channels:
            - deprecation
        handlers:
            main:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
                channels: ["!event", "!console", "!deprecation"]
